### ISSUE TITLE
ドローン衝突イベント検出時のPDUデータを作成する

### ISSUE THREAD

**Issue by tmori** [toppers/hakoniwa-ros2pdu#7]
# 概要

現状、ドローンの位置情報は、Twistでもらっている。
一方で、Unity上で発生したイベントを戻すにはどうすべきか悩んでいる。

案1. Twistで返す？
案2. 将来的な拡張性を考慮して、HakoUnityEvent的なデータ型を作る？

**Comment by tmori** [comment]
# 結論

案２にします。
将来的な拡張要件がドンドンくるような気がした。
少なくとも、衝突フラグは必要だと思うし。

**Comment by tmori** [comment]
名前：hako_msgs/Collision
データ型：

```
bool collision
double x
double y
double z
```

**Comment by tmori** [comment]
ROSだとデータ型はこうしないとダメだった。

```
bool collision
uint32 contact_num
geometry_msgs/Point[10] contact_position
float64 restitution_coefficient
```

**Comment by kenjihiranabe** [comment]
通信データの仕様決めは結構大変ですね。(後で変更しにくいし)
relativeVelocity も入れておいた方が良いよ。

**Comment by tmori** [comment]
潜在バグを見つけてしまった。。

https://github.com/toppers/hakoniwa-ros2pdu/issues/8

**Comment by tmori** [comment]
修正後：relative_velocityを追加

bool collision
uint32 contact_num
geometry_msgs/Vector3 relative_velocity
geometry_msgs/Point[10] contact_position
float64 restitution_coefficient
